import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-monteserrat",
  subsets: ["latin"],
});
const nura = localFont({
  src: "../public/fonts/Nura_Medium.ttf",
  variable: "--font-nura",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.className} ${nura.variable} font-monteserrat antialiased bg-muted`}
      >
          {children}
      </body>
    </html>
  );
}
