import type { Metadata } from "next";
import { Toaster } from "sonner";
import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <section>
        <Navbar />
        <Toaster position="top-center" richColors />
        {children}
        <Footer />
      </section>
  );
}
